import type { Country } from '../schemas/game-state';

// Top 50 countries by GDP with realistic 2024 data
// Remaining countries use simplified defaults
export const INITIAL_COUNTRIES: Record<string, Omit<Country, 'relations'>> = {
  'United States': {
    name: 'United States',
    displayName: 'United States of America',
    gdp: 28781,
    population: 334,
    stability: 75,
    military: { strength: 1000, nuclearCapable: true, defenseBudget: 886 },
    territories: ['US_MAINLAND', 'US_ALASKA', 'US_HAWAII'],
    government: 'Federal Republic',
    leader: 'President',
    color: '#3B82F6',
  },
  'China': {
    name: 'China',
    displayName: "People's Republic of China",
    gdp: 18533,
    population: 1412,
    stability: 80,
    military: { strength: 850, nuclearCapable: true, defenseBudget: 296 },
    territories: ['CN_MAINLAND'],
    government: 'One-Party Socialist Republic',
    leader: 'President',
    color: '#EF4444',
  },
  'Germany': {
    name: 'Germany',
    displayName: 'Federal Republic of Germany',
    gdp: 4459,
    population: 84,
    stability: 82,
    military: { strength: 280, nuclearCapable: false, defenseBudget: 75 },
    territories: ['DE_MAINLAND'],
    government: 'Federal Republic',
    leader: 'Chancellor',
    color: '#1F2937',
  },
  'Japan': {
    name: 'Japan',
    displayName: 'Japan',
    gdp: 4213,
    population: 125,
    stability: 88,
    military: { strength: 300, nuclearCapable: false, defenseBudget: 53 },
    territories: ['JP_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#FBBF24',
  },
  'India': {
    name: 'India',
    displayName: 'Republic of India',
    gdp: 3937,
    population: 1441,
    stability: 65,
    military: { strength: 600, nuclearCapable: true, defenseBudget: 83 },
    territories: ['IN_MAINLAND'],
    government: 'Federal Republic',
    leader: 'Prime Minister',
    color: '#F97316',
  },
  'United Kingdom': {
    name: 'United Kingdom',
    displayName: 'United Kingdom of Great Britain and Northern Ireland',
    gdp: 3496,
    population: 68,
    stability: 78,
    military: { strength: 350, nuclearCapable: true, defenseBudget: 75 },
    territories: ['GB_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#6366F1',
  },
  'France': {
    name: 'France',
    displayName: 'French Republic',
    gdp: 3131,
    population: 68,
    stability: 70,
    military: { strength: 370, nuclearCapable: true, defenseBudget: 60 },
    territories: ['FR_MAINLAND'],
    government: 'Semi-Presidential Republic',
    leader: 'President',
    color: '#2563EB',
  },
  'Italy': {
    name: 'Italy',
    displayName: 'Italian Republic',
    gdp: 2255,
    population: 59,
    stability: 68,
    military: { strength: 220, nuclearCapable: false, defenseBudget: 32 },
    territories: ['IT_MAINLAND'],
    government: 'Parliamentary Republic',
    leader: 'Prime Minister',
    color: '#22C55E',
  },
  'Brazil': {
    name: 'Brazil',
    displayName: 'Federative Republic of Brazil',
    gdp: 2174,
    population: 216,
    stability: 60,
    military: { strength: 250, nuclearCapable: false, defenseBudget: 22 },
    territories: ['BR_MAINLAND'],
    government: 'Federal Republic',
    leader: 'President',
    color: '#16A34A',
  },
  'Canada': {
    name: 'Canada',
    displayName: 'Canada',
    gdp: 2140,
    population: 40,
    stability: 85,
    military: { strength: 150, nuclearCapable: false, defenseBudget: 27 },
    territories: ['CA_MAINLAND'],
    government: 'Federal Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#DC2626',
  },
  'Russia': {
    name: 'Russia',
    displayName: 'Russian Federation',
    gdp: 2021,
    population: 144,
    stability: 55,
    military: { strength: 900, nuclearCapable: true, defenseBudget: 109 },
    territories: ['RU_MAINLAND'],
    government: 'Federal Semi-Presidential Republic',
    leader: 'President',
    color: '#7C3AED',
  },
  'South Korea': {
    name: 'South Korea',
    displayName: 'Republic of Korea',
    gdp: 1713,
    population: 52,
    stability: 80,
    military: { strength: 350, nuclearCapable: false, defenseBudget: 48 },
    territories: ['KR_MAINLAND'],
    government: 'Presidential Republic',
    leader: 'President',
    color: '#0EA5E9',
  },
  'Australia': {
    name: 'Australia',
    displayName: 'Commonwealth of Australia',
    gdp: 1688,
    population: 26,
    stability: 87,
    military: { strength: 180, nuclearCapable: false, defenseBudget: 32 },
    territories: ['AU_MAINLAND'],
    government: 'Federal Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#D97706',
  },
  'Mexico': {
    name: 'Mexico',
    displayName: 'United Mexican States',
    gdp: 1789,
    population: 130,
    stability: 55,
    military: { strength: 150, nuclearCapable: false, defenseBudget: 8 },
    territories: ['MX_MAINLAND'],
    government: 'Federal Republic',
    leader: 'President',
    color: '#059669',
  },
  'Spain': {
    name: 'Spain',
    displayName: 'Kingdom of Spain',
    gdp: 1582,
    population: 48,
    stability: 72,
    military: { strength: 200, nuclearCapable: false, defenseBudget: 20 },
    territories: ['ES_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#B91C1C',
  },
  'Indonesia': {
    name: 'Indonesia',
    displayName: 'Republic of Indonesia',
    gdp: 1417,
    population: 277,
    stability: 62,
    military: { strength: 200, nuclearCapable: false, defenseBudget: 9 },
    territories: ['ID_MAINLAND'],
    government: 'Presidential Republic',
    leader: 'President',
    color: '#BE185D',
  },
  'Saudi Arabia': {
    name: 'Saudi Arabia',
    displayName: 'Kingdom of Saudi Arabia',
    gdp: 1109,
    population: 36,
    stability: 75,
    military: { strength: 250, nuclearCapable: false, defenseBudget: 75 },
    territories: ['SA_MAINLAND'],
    government: 'Absolute Monarchy',
    leader: 'King',
    color: '#15803D',
  },
  'Netherlands': {
    name: 'Netherlands',
    displayName: 'Kingdom of the Netherlands',
    gdp: 1093,
    population: 18,
    stability: 85,
    military: { strength: 120, nuclearCapable: false, defenseBudget: 15 },
    territories: ['NL_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#EA580C',
  },
  'Turkey': {
    name: 'Turkey',
    displayName: 'Republic of Türkiye',
    gdp: 1108,
    population: 85,
    stability: 55,
    military: { strength: 400, nuclearCapable: false, defenseBudget: 18 },
    territories: ['TR_MAINLAND'],
    government: 'Presidential Republic',
    leader: 'President',
    color: '#991B1B',
  },
  'Switzerland': {
    name: 'Switzerland',
    displayName: 'Swiss Confederation',
    gdp: 905,
    population: 9,
    stability: 95,
    military: { strength: 80, nuclearCapable: false, defenseBudget: 6 },
    territories: ['CH_MAINLAND'],
    government: 'Federal Republic',
    leader: 'Federal Council',
    color: '#E11D48',
  },
  'Poland': {
    name: 'Poland',
    displayName: 'Republic of Poland',
    gdp: 842,
    population: 38,
    stability: 70,
    military: { strength: 200, nuclearCapable: false, defenseBudget: 32 },
    territories: ['PL_MAINLAND'],
    government: 'Parliamentary Republic',
    leader: 'President',
    color: '#F43F5E',
  },
  'Argentina': {
    name: 'Argentina',
    displayName: 'Argentine Republic',
    gdp: 641,
    population: 46,
    stability: 45,
    military: { strength: 120, nuclearCapable: false, defenseBudget: 5 },
    territories: ['AR_MAINLAND'],
    government: 'Federal Republic',
    leader: 'President',
    color: '#38BDF8',
  },
  'Sweden': {
    name: 'Sweden',
    displayName: 'Kingdom of Sweden',
    gdp: 599,
    population: 10,
    stability: 88,
    military: { strength: 100, nuclearCapable: false, defenseBudget: 10 },
    territories: ['SE_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#FACC15',
  },
  'Norway': {
    name: 'Norway',
    displayName: 'Kingdom of Norway',
    gdp: 554,
    population: 5,
    stability: 92,
    military: { strength: 80, nuclearCapable: false, defenseBudget: 9 },
    territories: ['NO_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#1E40AF',
  },
  'Israel': {
    name: 'Israel',
    displayName: 'State of Israel',
    gdp: 525,
    population: 10,
    stability: 55,
    military: { strength: 400, nuclearCapable: true, defenseBudget: 24 },
    territories: ['IL_MAINLAND'],
    government: 'Parliamentary Republic',
    leader: 'Prime Minister',
    color: '#1D4ED8',
  },
  'Nigeria': {
    name: 'Nigeria',
    displayName: 'Federal Republic of Nigeria',
    gdp: 477,
    population: 224,
    stability: 40,
    military: { strength: 150, nuclearCapable: false, defenseBudget: 3 },
    territories: ['NG_MAINLAND'],
    government: 'Federal Republic',
    leader: 'President',
    color: '#166534',
  },
  'Iran': {
    name: 'Iran',
    displayName: 'Islamic Republic of Iran',
    gdp: 404,
    population: 88,
    stability: 45,
    military: { strength: 350, nuclearCapable: false, defenseBudget: 25 },
    territories: ['IR_MAINLAND'],
    government: 'Theocratic Republic',
    leader: 'Supreme Leader',
    color: '#065F46',
  },
  'Egypt': {
    name: 'Egypt',
    displayName: 'Arab Republic of Egypt',
    gdp: 398,
    population: 105,
    stability: 50,
    military: { strength: 300, nuclearCapable: false, defenseBudget: 8 },
    territories: ['EG_MAINLAND'],
    government: 'Presidential Republic',
    leader: 'President',
    color: '#CA8A04',
  },
  'Ukraine': {
    name: 'Ukraine',
    displayName: 'Ukraine',
    gdp: 179,
    population: 37,
    stability: 35,
    military: { strength: 350, nuclearCapable: false, defenseBudget: 44 },
    territories: ['UA_MAINLAND'],
    government: 'Semi-Presidential Republic',
    leader: 'President',
    color: '#2563EB',
  },
  'Pakistan': {
    name: 'Pakistan',
    displayName: 'Islamic Republic of Pakistan',
    gdp: 374,
    population: 230,
    stability: 38,
    military: { strength: 400, nuclearCapable: true, defenseBudget: 10 },
    territories: ['PK_MAINLAND'],
    government: 'Federal Republic',
    leader: 'Prime Minister',
    color: '#047857',
  },
  'North Korea': {
    name: 'North Korea',
    displayName: "Democratic People's Republic of Korea",
    gdp: 18,
    population: 26,
    stability: 65,
    military: { strength: 300, nuclearCapable: true, defenseBudget: 4 },
    territories: ['KP_MAINLAND'],
    government: 'One-Party Republic',
    leader: 'Supreme Leader',
    color: '#4C1D95',
  },
  'South Africa': {
    name: 'South Africa',
    displayName: 'Republic of South Africa',
    gdp: 399,
    population: 60,
    stability: 48,
    military: { strength: 120, nuclearCapable: false, defenseBudget: 4 },
    territories: ['ZA_MAINLAND'],
    government: 'Parliamentary Republic',
    leader: 'President',
    color: '#4ADE80',
  },
  'Thailand': {
    name: 'Thailand',
    displayName: 'Kingdom of Thailand',
    gdp: 515,
    population: 72,
    stability: 58,
    military: { strength: 180, nuclearCapable: false, defenseBudget: 8 },
    territories: ['TH_MAINLAND'],
    government: 'Constitutional Monarchy',
    leader: 'Prime Minister',
    color: '#7E22CE',
  },
  'Colombia': {
    name: 'Colombia',
    displayName: 'Republic of Colombia',
    gdp: 363,
    population: 52,
    stability: 50,
    military: { strength: 130, nuclearCapable: false, defenseBudget: 10 },
    territories: ['CO_MAINLAND'],
    government: 'Presidential Republic',
    leader: 'President',
    color: '#FDE047',
  },
  'Vietnam': {
    name: 'Vietnam',
    displayName: 'Socialist Republic of Vietnam',
    gdp: 449,
    population: 99,
    stability: 70,
    military: { strength: 180, nuclearCapable: false, defenseBudget: 7 },
    territories: ['VN_MAINLAND'],
    government: 'One-Party Socialist Republic',
    leader: 'President',
    color: '#DC2626',
  },
};

// Generate default country data for remaining countries on demand
export function getDefaultCountry(name: string): Omit<Country, 'relations'> {
  return {
    name,
    displayName: name,
    gdp: 50,
    population: 10,
    stability: 50,
    military: { strength: 50, nuclearCapable: false, defenseBudget: 1 },
    territories: [`${name.replace(/\s+/g, '_').toUpperCase()}_MAINLAND`],
    government: 'Republic',
    leader: 'Leader',
    color: '#9CA3AF',
  };
}

// All selectable country names (top 35 for MVP)
export const SELECTABLE_COUNTRIES = Object.keys(INITIAL_COUNTRIES);
